### ISSUE TITLE
Standardnotes / standardfile

### ISSUE THREAD

**Issue by BobTB** [Dryusdan/Dockerfiles#3]
Is your standardnotes the web client for the standardfile server or just another "standardfile" server?  It does not expose any ports.

**Comment by Dryusdan** [comment]
Standardnotes is a web client for standardfile server. 
Hum... Ho, I forgot readme.me on standardfile server 😶 

Today it work with this docker-compose : 
```
  standardfile:
    image: dryusdan/standardfile
    env_file: /home/docker/services/standardfiles/.env.app.production
    restart: always
    volumes:
      - /home/docker/services/standardfiles/data:/data/src/public
      - /etc/localtime:/etc/localtime:ro

		
  nginx-standardfile:
    restart: always
    image: xataz/nginx

    links:
      - standardfile:app
    volumes:
      - /home/docker/web/drycat.fr/standardfile/nginx/sites-enabled:/nginx/sitess
-enabled
      - /home/docker/web/drycat.fr/standardfile/nginx/log:/nginx/log
      - /etc/localtime:/etc/localtime:ro

```
And this sites-enabled/standarfiles.conf
```
upstream puma_sample_rails_docker_app {
  server app:3000;
}

server {

  listen 8080;

  client_max_body_size 4G;
  keepalive_timeout 10;

  error_page 500 502 504 /500.html;
  error_page 503 @503;

  server_name localhost puma_sample_rails_docker_app;
  root /data/src/public;
  try_files $uri/index.html $uri @puma_sample_rails_docker_app;

  location @puma_sample_rails_docker_app {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
	proxy_pass http://puma_sample_rails_docker_app;
    # limit_req zone=one;
  }

  location ^~ /assets/ {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }

  location = /50x.html {
    root html;
  }

  location = /404.html {
    root html;
  }

  location @503 {
    error_page 405 = /system/maintenance.html;
    if (-f $document_root/system/maintenance.html) {
	  rewrite ^(.*)$ /system/maintenance.html break;
    }
    rewrite ^(.*)$ /503.html break;
  }

  if ($request_method !~ ^(GET|HEAD|PUT|PATCH|POST|DELETE|OPTIONS)$ ){
    return 405;
  }

  if (-f $document_root/system/maintenance.html) {
    return 503;
  }

  location ~ \.(php|html)$ {
    return 405;
  }
}
```


But, it's today... I think, later I compress both in one container :grin:
